# Generated by Django 5.2.6 on 2025-09-19 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_hours_off_duty', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_hours_sleeper', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_hours_driving', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_hours_on_duty', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_cycle_hours', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('driver_name', models.CharField(max_length=100)),
                ('carrier_name', models.CharField(max_length=200)),
                ('truck_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='eld_app.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('segment_type', models.CharField(choices=[('driving', 'Driving'), ('rest', 'Rest'), ('fuel', 'Fuel Stop'), ('pickup', 'Pickup'), ('dropoff', 'Drop-off'), ('break', '30-min Break')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='eld_app.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='eld_app.trip'),
        ),
    ]
